#!/bin/bash

# Name of the application
NAME="upraised_backend"

# Django project directory
DJANGODIR=/var/app

# The user to run as
USER=django_user

# The group to run as
GROUP=django_user

# How many worker processes should Gunicorn spawn
NUM_WORKERS=1
TIMEOUT=300

# WSGI module name
DJANGO_WSGI_MODULE=$NAME.wsgi
echo "Starting $NAME as $(whoami)"

# Full path to gunicorn
GUNICORN_PATH=$(python -m site --user-base)/bin/gunicorn

# Bind options
if [ "$ENVIRONMENT" = "production" ]; then
    BIND="unix:$SOCKFILE"
else
    BIND="0.0.0.0:8000"
fi

# Start your Django Unicorn
# Programs meant to be run under supervisor should not daemonize themselves (do not use --daemon)
exec $GUNICORN_PATH ${DJANGO_WSGI_MODULE}:application \
--name $NAME \
--workers $NUM_WORKERS \
--timeout $TIMEOUT \
--user=$USER \
--group=$GROUP \
--bind=$BIND \
--log-level=debug \
--log-file=/var/app/logs/gunicorn.err.log \
--capture-output
